### ISSUE TITLE
Missing engine functions to remove Plugs and Circuits.

### ISSUE THREAD

**Issue by pouzzler** [pouzzler/IED-Logic-Simulator#3]
It is necessary to have engine function that remove Plugs and Circuits, as it is expected a user will "play around" the MainView, and add an remove items at will. The logic for these deletions must reside in the engine, not the gui.

**Comment by mathieufrh** [comment]
The remove method has been implemented in the Circuit class ans can emove input, output and sub-circuit from a Circuit object.
