### ISSUE TITLE
Logging improvements

### ISSUE THREAD

**Issue by pouzzler** [pouzzler/IED-Logic-Simulator#5]
Logging towards a file, and towards stdout/stderr must be enabled.
Logging granularity must be improved : each or almost each engine log message needs a boolean flag to enable/disable it.
The GUI must present options to activate these two things, probably in the main menu.

**Comment by mathieufrh** [comment]
Add multi log support toward file and stdout (DEBUG level for the file handler ERROR level for the stdout heangler).
